#!/bin/bash

ONEZONE_IP="$1"

# Regular expression to match IPv4 address
REGEX="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

if [[ $ONEZONE_IP =~ $REGEX ]]; then
    exec /root/oneprovider.sh demo $ONEZONE_IP
else
    echo "$ONEZONE_IP does not look like a valid IP address. Exiting..."
    exit 1
fi
