#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import os
import re
import subprocess as sp
import sys
import textwrap
import time

import requests
import yaml
from requests import codes
from requests.packages.urllib3.exceptions import InsecureRequestWarning

try:
    import xml.etree.cElementTree as eTree
except ImportError:
    import xml.etree.ElementTree as eTree

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)


# -----------------------------------------------------------------------------
# Components & logging
# -----------------------------------------------------------------------------

COMPONENTS = ["cluster_manager", "op_panel", "op_worker"]

LOGS = [
    ("[op_panel]", "/var/log/op_panel"),
    ("[cluster_manager]", "/var/log/cluster_manager"),
    ("[op_worker]", "/var/log/op_worker"),
]
LOG_LEVELS = ["debug", "info", "error"]


# -----------------------------------------------------------------------------
# Environment / authentication
# -----------------------------------------------------------------------------

# If onepanel is started from sources, contains the path to the root directory
# of the pre-built onepanel repo/artifact.
ONEPANEL_OVERRIDE = "ONEPANEL_OVERRIDE"

# Username for Basic auth with the emergency passphrase
PASSPHRASE_USERNAME = "onepanel"
EMERGENCY_PASSPHRASE_VARIABLE = "ONEPANEL_EMERGENCY_PASSPHRASE"


# -----------------------------------------------------------------------------
# Paths – sources (build/override)
# -----------------------------------------------------------------------------

LEGACY_VM_ARGS_SOURCES_PATH_TEMPLATE = "_build/default/rel/{component}/etc/vm.args"

ONP_GENERATED_CONFIG_SOURCES_PATH = (
    "_build/default/rel/op_panel/etc/autogenerated.config"
)
ONP_VM_ARGS_SOURCES_PATH = "_build/default/rel/op_panel/etc/autogenerated.vm.args"
ONP_BIN_SOURCES_PATH = "_build/default/rel/op_panel/bin/op_panel"


# -----------------------------------------------------------------------------
# Paths – packages (installed)
# -----------------------------------------------------------------------------

LEGACY_VM_ARGS_PACKAGES_PATH_TEMPLATE = "/etc/{component}/vm.args"

ONP_GENERATED_CONFIG_PACKAGES_PATH = "/etc/op_panel/autogenerated.config"
ONP_VM_ARGS_PACKAGES_PATH = "/etc/op_panel/autogenerated.vm.args"


# -----------------------------------------------------------------------------
# Templates & formatting
# -----------------------------------------------------------------------------

AUTOGENERATED_VM_ARGS_TEMPLATE = """# MACHINE GENERATED FILE. DO NOT MODIFY.

## Name of the node
-name {node}

## Cookie for distributed erlang
-setcookie {cookie}
"""

WRAP_KWARGS = {"width": 100, "break_long_words": False, "break_on_hyphens": False}


# -----------------------------------------------------------------------------
# Runtime / persistence
# -----------------------------------------------------------------------------

ONEPANEL_BASE_URL = "https://127.0.0.1:9443"

# Used by the "await" script to signal service readiness
SERVICE_READY_LOCK_FILE = "/root/service-ready.lock"

# Persistence detection (fresh vs existing deployment)
COUCHBASE_DATA_DIR = "/opt/couchbase/var/lib/couchbase/data"


# -----------------------------------------------------------------------------
# User-facing messages
# -----------------------------------------------------------------------------
MSG_CONGRATULATIONS = (
    "\nCongratulations! New Oneprovider deployment successfully started."
)
MSG_WAITING_FOR_CLUSTER = "\nWaiting for existing cluster to start..."
MSG_WAITING_FOR_PANEL = (
    "Waiting for op_panel server to be available\n"
    "(may require starting other cluster nodes)\n"
)
MSG_RESUMED_WORK = "Existing Oneprovider deployment resumed work."
MSG_AUTHENTICATION_ERROR = (
    "The launch script cannot access onepanel to manage the deployment process.\n"
    "Please ensure that valid emergency passphrase is present\n"
    f"in the {EMERGENCY_PASSPHRASE_VARIABLE} environment variable\n"
    "or oversee the cluster status manually."
)
MSG_MISSING_EXISTING_PASSPHRASE = (
    f"Environment variable {EMERGENCY_PASSPHRASE_VARIABLE} is missing.\n"
    "An existing deployment will continue to work\n"
    "but this script will not be able to track its startup.\n"
    "You can fix this by setting the variable\n"
    "to the Onepanel' passphrase (formerly admin account's password)."
)
MSG_MISSING_NEW_PASSPHRASE = (
    f"Environment variable {EMERGENCY_PASSPHRASE_VARIABLE} is missing.\n"
    "When deploying a new cluster this variable is required.\n"
    "Please set it to your desired Onepanel emergency passphrase.\n"
)
MSG_FAILURE_DUMP_LOGS = (
    "\n"
    "Below is a dump of all application logs at the moment of failure:\n"
    "-------------------------------------------------------------\n"
)
MSG_FAILURE_FOOTER = (
    "-------------------------------------------------------------\n"
    "ERROR: Starting the container failed - see above."
)


class MissingVariableError(Exception):
    """Raised when a required environment variable is not set."""

    def __init__(self, variable_name):
        message = "Missing {} environment variable".format(variable_name)
        super().__init__(message)
        self.variable_name = variable_name


class AuthenticationError(Exception):
    """Raised when an API request is rejected due to invalid credentials."""


def main():
    current_log_level = os.environ.get("ONEPANEL_LOG_LEVEL", "info").lower()
    try:
        preconfigure()
        start_onepanel()

        if env_bool("ONEPANEL_BATCH_MODE"):
            configure_deployment()

        # show_details()  NOTE: currently not working correctly (all details are null)
    except Exception as e:
        log("\nERROR: {0}".format(e))
        if env_bool("ONEPANEL_DEBUG_MODE"):
            # Keep container running for inspection; do not dump logs or exit
            pass
        else:
            log(MSG_FAILURE_DUMP_LOGS)
            print_logs(current_log_level, infinitely=False)
            log(MSG_FAILURE_FOOTER)
            sys.exit(1)

    previous_log_cursors = print_logs(current_log_level, infinitely=False)
    with open(SERVICE_READY_LOCK_FILE, "w"):
        pass
    print_logs(
        current_log_level, starting_log_cursors=previous_log_cursors, infinitely=True
    )


def preconfigure():
    """Prepare app.cconfig and vm.args."""
    upgrade_legacy_vm_args_if_exists()

    override_path = get_env(ONEPANEL_OVERRIDE)
    if override_path:
        app_config_path = os.path.join(override_path, ONP_GENERATED_CONFIG_SOURCES_PATH)
        vm_args_path = os.path.join(override_path, ONP_VM_ARGS_SOURCES_PATH)
    else:
        app_config_path = ONP_GENERATED_CONFIG_PACKAGES_PATH
        vm_args_path = ONP_VM_ARGS_PACKAGES_PATH

    if not config_file_initialized(app_config_path):
        generate_config_file(app_config_path)

    set_node_name(vm_args_path)


def upgrade_legacy_vm_args_if_exists():
    override_path = get_env(ONEPANEL_OVERRIDE)
    if override_path:
        legacy_vm_args_path_template = os.path.join(
            override_path,
            "../{component}",
            LEGACY_VM_ARGS_SOURCES_PATH_TEMPLATE,
        )
    else:
        legacy_vm_args_path_template = LEGACY_VM_ARGS_PACKAGES_PATH_TEMPLATE

    for component in COMPONENTS:
        legacy_vm_args_path = legacy_vm_args_path_template.format(component=component)

        if os.path.exists(legacy_vm_args_path):
            upgrade_legacy_vm_args(legacy_vm_args_path)


def upgrade_legacy_vm_args(legacy_vm_args_path):
    with open(legacy_vm_args_path, "r") as f:
        content = f.read()

    node = re.search(r"-name (?P<node>.*)", content).group("node")
    cookie = re.search(r"-setcookie (?P<cookie>.*)", content).group("cookie")

    autogenerated_vm_args_path = os.path.join(
        os.path.dirname(legacy_vm_args_path), "autogenerated.vm.args"
    )

    with open(autogenerated_vm_args_path, "w") as f:
        f.write(AUTOGENERATED_VM_ARGS_TEMPLATE.format(node=node, cookie=cookie))

    os.remove(legacy_vm_args_path)

    log(
        f"Upgraded legacy vm.args: {legacy_vm_args_path} -> {autogenerated_vm_args_path}"
    )


def config_file_initialized(file_path):
    try:
        with open(file_path, "r") as f:
            content = f.read()
            return bool(re.search(r"{config_initialized,\s*true}", content))
    except OSError:
        return False


def generate_config_file(file_path):
    content = (
        "% MACHINE GENERATED FILE. DO NOT MODIFY.\n"
        "% Use overlay.config for custom configuration.\n\n"
        "[{onepanel, [{config_initialized, true}"
    )

    if get_env("ONEPANEL_GENERATE_TEST_WEB_CERT"):
        domain = get_env("ONEPANEL_GENERATED_CERT_DOMAIN", "")
        flag = str(env_bool("ONEPANEL_GENERATE_TEST_WEB_CERT")).lower()
        content += f",\n{{generate_test_web_cert, {flag}}}"
        content += f',\n{{test_web_cert_domain, "{domain}"}}'

    if get_env("ONEPANEL_TRUST_TEST_CA"):
        flag = str(env_bool("ONEPANEL_TRUST_TEST_CA")).lower()
        content += f",\n{{treat_test_ca_as_trusted, {flag}}}"

    content += "\n]}]."

    with open(file_path, "w") as f:
        f.write(content)


def set_node_name(file_path):
    hostname = sp.check_output(["hostname", "-f"]).decode().rstrip("\n")
    replace(file_path, r"-name .*", "-name onepanel@{0}".format(hostname))


def start_onepanel():
    log("Starting op_panel...")

    cmd = ["service", "op_panel", "start"]
    override_path = get_env(ONEPANEL_OVERRIDE)
    if override_path:
        op_panel_script = os.path.join(override_path, ONP_BIN_SOURCES_PATH)
        cmd = [op_panel_script, "start"]

    try:
        sp.check_output(cmd)
    except sp.CalledProcessError as err:
        log("ERROR: " + str(err))
        log("Output was:\n")
        log(str(err.output))
        sys.exit(err.returncode)

    wait_for_rest_listener()
    log("[  OK  ] op_panel started")


def wait_for_rest_listener():
    first = True
    connected = False
    while not connected:
        try:
            requests.get(f"{ONEPANEL_BASE_URL}/api/v3/onepanel/", verify=False)
        except requests.ConnectionError:
            if first:
                log(MSG_WAITING_FOR_PANEL)
                first = False
            time.sleep(1)
        else:
            connected = True


def configure_deployment():
    batch_config = get_batch_config()
    try:
        if configure(batch_config):
            log(MSG_CONGRATULATIONS)
        else:
            log(MSG_WAITING_FOR_CLUSTER)
            wait_for_workers()
            log(MSG_RESUMED_WORK)
    except AuthenticationError:
        log(MSG_AUTHENTICATION_ERROR)
    except MissingVariableError as e:
        if e.variable_name != EMERGENCY_PASSPHRASE_VARIABLE:
            raise

        if is_fresh_install():
            # most likely this is an existing deployment
            log(MSG_MISSING_EXISTING_PASSPHRASE)
        else:
            log(MSG_MISSING_NEW_PASSPHRASE)


def get_batch_config():
    batch_config = get_env("ONEPROVIDER_CONFIG", "")
    batch_config = yaml.safe_load(batch_config)
    if not batch_config:
        return {}

    # insert interactiveDeployment mark if not present
    onepanel_config = batch_config.get("onepanel", {})
    if "interactiveDeployment" not in onepanel_config:
        onepanel_config["interactiveDeployment"] = False
        batch_config["onepanel"] = onepanel_config

    return batch_config


def configure(config):
    """
    Attempts to deploy the Oneprovider
    :return: False if configuration was skipped because of existing deployment,
        True upon success
    """
    passphrase = get_emergency_passphrase()

    try:
        set_emergency_passphrase(passphrase)
    except AuthenticationError:
        # emergency passphrase setup failure indicates existing deployment
        return False

    r = do_auth_request(
        requests.post,
        f"{ONEPANEL_BASE_URL}/api/v3/onepanel/provider/configuration",
        headers={"content-type": "application/x-yaml"},
        data=yaml.dump(config),
        verify=False,
    )

    if r.status_code == codes.conflict:
        return False

    if not r.ok:
        raise RuntimeError(
            "Failed to start configuration process, the response was:\n"
            "  code: {0}\n"
            "  body: {1}\n"
            "For more information please check the logs.".format(r.status_code, r.text)
        )

    loc = r.headers["location"]
    status = "running"
    steps = []
    resp = {}

    log("\nConfiguring Oneprovider:")
    while status == "running":
        r = do_auth_request(requests.get, ONEPANEL_BASE_URL + loc, verify=False)
        if not r.ok:
            raise RuntimeError(
                "Unexpected configuration error\n{0}"
                "For more information please check the logs.".format(r.text)
            )

        resp = json.loads(r.text)
        status = resp.get("status", "error")
        for step in resp.get("steps", []):
            if steps and step == steps[0]:
                steps = steps[1:]
            else:
                log(format_step(step))
        steps = resp.get("steps", [])
        time.sleep(1)

    if status != "ok":
        raise RuntimeError(format_error(resp))
    return True


def get_emergency_passphrase():
    passphrase = get_env(EMERGENCY_PASSPHRASE_VARIABLE)
    if passphrase is None:
        raise MissingVariableError(EMERGENCY_PASSPHRASE_VARIABLE)
    return passphrase


def set_emergency_passphrase(passphrase):
    r = requests.put(
        f"{ONEPANEL_BASE_URL}/api/v3/onepanel/emergency_passphrase",
        headers={"content-type": "application/json"},
        data=json.dumps({"newPassphrase": passphrase}),
        verify=False,
    )
    if r.status_code in (codes.unauthorized, codes.forbidden):
        raise AuthenticationError(
            "Could not set Onepanel emergency passphrase due to "
            f"authentication error: {r.status_code} {r.text}"
        )
    if not r.ok:
        raise RuntimeError(
            f"Could not set Onepanel emergency passphrase: {r.status_code} {r.text}"
        )


def do_auth_request(request, *args, **kwargs):
    passphrase = get_emergency_passphrase()
    r = request(*args, auth=(PASSPHRASE_USERNAME, passphrase), **kwargs)
    if r.status_code in (codes.unauthorized, codes.forbidden):
        raise AuthenticationError(
            "Authentication error.\n"
            "Please ensure that valid emergency passphrase is present\n"
            f"in the {EMERGENCY_PASSPHRASE_VARIABLE} environment variable"
        )
    return r


def wait_for_workers():
    url = f"{ONEPANEL_BASE_URL}/api/v3/onepanel/provider/nagios"
    retries = 0
    while not nagios_up(url, retries % 10 == 9):
        time.sleep(1)
        retries += 1
        if retries == 120:
            raise RuntimeError("Timeout waiting for the Onepanel service readiness")


def nagios_up(url, log_errors=False):
    try:
        r = do_auth_request(requests.get, url, verify=False)
        if not r.ok:
            if log_errors:
                log(
                    "Onepanel service is reachable, but nagios is not reporting an OK status - retrying..."
                )
            return False
    except Exception:
        if log_errors:
            log("Onepanel service is not reachable - retrying...")
        return False

    healthdata = eTree.fromstring(r.text)
    return healthdata.attrib["status"] == "ok"


def show_details():
    log("\nContainer details:")

    container_id = get_container_id()
    json = inspect_container(container_id)

    show_ip_address(json)
    show_ports(json)


def get_container_id():
    with open("/proc/self/cgroup", "r") as f:
        return f.readline().split("/")[-1].rstrip("\n")


def inspect_container(container_id):
    try:
        result = sp.check_output(
            [
                "curl",
                "-s",
                "--unix-socket",
                "/var/run/docker.sock",
                "http:/containers/{0}/json".format(container_id),
            ]
        )
        return json.loads(result)
    except Exception:
        return {}


def show_ip_address(json):
    ip = "-"
    try:
        ip = list(json["NetworkSettings"]["Networks"].items())[0][1]["IPAddress"]
    except (KeyError, IndexError, TypeError):
        try:
            ip = sp.check_output(["hostname", "-i"]).decode().rstrip("\n")
        except Exception:
            pass
    log("* IP Address: {0}".format(ip))


def show_ports(json):
    ports = json.get("NetworkSettings", {}).get("Ports", {})
    ports_format = []
    for container_port in ports:
        host = ports[container_port]
        if host:
            for host_port in host:
                ports_format.append(
                    "{0}:{1} -> {2}".format(
                        host_port["HostIp"], host_port["HostPort"], container_port
                    )
                )
        else:
            ports_format.append(container_port)
    ports_str = "\n         ".join(ports_format) if ports_format else "-"
    log("* Ports: {0}".format(ports_str))


def format_step(step):
    service, action = step.split(":")
    return "* {0}: {1}".format(service, action)


def format_error(response):
    if "error" not in response:
        return "Error: unexpected server response"
    error_obj = response["error"]
    error_id, descr, details, nodes = unwrap_error_with_hosts(error_obj)
    details_str = format_dict(details, "    ")

    if details_str:
        details_str = "  details:\n" + details_str
    nodes_str = ""
    if nodes:
        nodes_str = "  nodes:\n    " + "\n    ".join(sorted(nodes))
    descr_str = textwrap.fill(
        "description: " + descr,
        initial_indent="  ",
        subsequent_indent="    ",
        **WRAP_KWARGS,
    )
    return "Error:\n  id: {}\n{}\n{}\n{}".format(
        error_id, nodes_str, descr_str, details_str
    )


def format_dict(details, indent):
    result = ""
    for key, value in list(details.items()):
        if isinstance(value, dict):
            result += indent + "{}:\n".format(key)
            result += format_dict(value, indent + "  ")
        else:
            result += (
                textwrap.fill(
                    "{}: {}".format(key, value),
                    initial_indent=indent,
                    subsequent_indent=indent + "  ",
                    **WRAP_KWARGS,
                )
                + "\n"
            )
    return result


def unwrap_error_with_hosts(error_obj):
    """Extracts original error from a wrapper listing hosts
    where the error occurred"""
    error_id = error_obj.get("id")
    description = error_obj.get("description")
    details = error_obj.get("details", {})
    nodes = []

    if error_id == "errorOnNodes" and "error" in details:
        error_id = details["error"]["id"]
        description = details["error"]["description"]
        nodes = details["hostnames"]
        details = details["error"].get("details", {})

    return error_id, description, details, nodes


def print_logs(log_level, starting_log_cursors=None, infinitely=True):
    # first run of the function
    if not isinstance(starting_log_cursors, list):
        starting_log_cursors = []
        if log_level in LOG_LEVELS:
            log("\nLogging on '{0}' level:".format(log_level))
            for log_prefix, log_dir in LOGS:
                log_file = os.path.join(log_dir, log_level + ".log")
                starting_log_cursors.append((log_prefix, log_file, None, None))
        else:
            log("\nLogging to stdout disabled (log level = {})".format(log_level))

    new_log_cursors = print_new_logs(starting_log_cursors)
    while infinitely:
        new_log_cursors = print_new_logs(new_log_cursors)
        time.sleep(1)
    return new_log_cursors


def print_new_logs(log_cursors):
    new_logs = []

    for log_prefix, log_file, log_fd, log_ino in log_cursors:
        try:
            if os.stat(log_file).st_ino != log_ino:
                if log_fd:
                    log_fd.close()
                log_fd = open(log_file, "r")
                log_ino = os.stat(log_file).st_ino

            log_line = log_fd.readline()
            while log_line:
                log("{0} {1}".format(log_prefix, log_line), end="")
                log_line = log_fd.readline()

            new_logs.append((log_prefix, log_file, log_fd, log_ino))
        except:
            new_logs.append((log_prefix, log_file, None, None))

    return new_logs


def is_fresh_install():
    """True if there is no preexisting persistence (fresh deployment)."""
    return not os.path.isdir(COUCHBASE_DATA_DIR)


def log(message, end="\n"):
    sys.stdout.write(message + end)
    sys.stdout.flush()


def replace(file_path, pattern, value):
    with open(file_path, "r+") as f:
        content = f.read()
        content = re.sub(pattern, value, content)
        f.seek(0)
        f.truncate()
        f.write(content)


def env_bool(key, default=False):
    return get_env(key, str(default)).lower() in ("true", "1")


def get_env(key, default=None):
    return os.environ.get(key, default)


if __name__ == "__main__":
    main()
