#!/bin/bash

source /root/demo-mode/better-curl.sh

# Optional first argument
TIMEOUT=${1:-300}

# demo-access-token waits for Onezone internally
ACCESS_TOKEN=$(demo-access-token)

RETRY_NUM=0
while ! do_curl -H "x-auth-token:$ACCESS_TOKEN" -X POST "https://127.0.0.1/api/v3/oneprovider/lookup-file-id/demo-space" > /dev/null; do
    RETRY_NUM=$((RETRY_NUM + 1))

    if ! ((RETRY_NUM % 15)); then
        echo -e "\e[1;33m"
        echo "-------------------------------------------------------------------------"
        echo "Waiting for the demo environment to be set up..."
        echo "-------------------------------------------------------------------------"
        echo -e "\e[0m"
    fi

    if [[ ${RETRY_NUM} -eq ${TIMEOUT} ]]; then
        echo -e "\e[1;31m"
        echo "-------------------------------------------------------------------------"
        echo "ERROR: The demo environment failed to be set up within ${TIMEOUT} seconds, exiting."
        echo "-------------------------------------------------------------------------"
        echo -e "\e[0m"
        exit 1
    fi

    sleep 1;
done

exit 0
