#!/bin/bash

# Regular expression to match IPv4 address
IP_REGEX="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

ONEZONE_IP="$1"

if [[ -z "${ONEZONE_IP}" ]]; then
    echo "ERROR: You must provide Onezone IP address as the first argument of the demo command, exiting."
    exit 1
fi

if [[ ${ONEZONE_IP} =~ $IP_REGEX ]]; then
    exec /root/oneprovider.sh demo "${ONEZONE_IP}"
else
    echo "ERROR: \"${ONEZONE_IP}\" does not look like a valid IP address, exiting."
    exit 1
fi
